package ex_14072024;

public class Lab53 {
    public static void main(String[] args) {


        byte b = 127;
//        1 byte - 8 bits...
        short s = 200;
//        2 bytes - 16 bits...
        int i = 150;
//        4 bytes - 32 bits...
        long l = 45000L;
//        8 bytes - 64 bits...
        char ch = 'a';
//        2 bytes - 16 bits...
        float f = 2.33f;
//        4 bytes - 32 bits...
        double d = 34500;
//        8 bytes - 64b bits...
        boolean bo = true;
//        1 byte - 8 bits...
        String st = "Deepak";
//        8 bytes - 64 bits...

        System.out.println();
    }
}
